<div>
    <h2><?php echo $this->__('processing_payment') ?>...</h2>

    <p><?php echo $this->__('auto_refresh') ?> 5 <?php echo $this->__('seconds') ?></p>
    <p><?php echo $this->__('next_refresh') ?> <span id="seconds-remaining">5</span> <?php echo $this->__('seconds') ?></p>

    <form action="<?php print $formAction; ?>" name="update_status" method="post">
        <input type="submit" value="<?php echo $this->__('check_result') ?>" />
    </form>
</div>
<script type="text/javascript">
    (function countdown()
    {
        if (document.getElementById("seconds-remaining").innerHTML > 0)
        {
            --document.getElementById("seconds-remaining").innerHTML;
            setTimeout(countdown, 1000);
        }
        else
        {
            document.update_status.submit();
        }
    })();
</script>